# Generated by Django 5.0 on 2023-12-17 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время старта рассылки')),
                ('next_date', models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время старта рассылки'), verbose_name='Время следующей рассылки')),
                ('end_date', models.DateTimeField(verbose_name='Время окончания рассылки')),
                ('interval', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=50, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], help_text='Создана/Завершена', max_length=50)),
                ('mail_to', models.ManyToManyField(to='sendmail.client', verbose_name='Клиент_кому')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sendmail.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, verbose_name='Время последней рассылки')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='Статус попытки')),
                ('response', models.TextField(default=None, null=True, verbose_name='Ответ сервера')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sendmail.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
    ]
