# Generated by Django 5.0 on 2023-12-18 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Действующая'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время следующей рассылки'),
        ),
    ]
