# Generated by Django 5.0 on 2023-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/preview/', verbose_name='Изображение')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('date_public', models.DateField(auto_now=True)),
            ],
        ),
    ]
